name: "CI CD"
on:
  release:
    types:
      - released

jobs:
  build-and-push-web:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Get Tag Number"
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        id: extract_tag

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: captainaldi/uptime-kuma-report:${{ steps.extract_tag.outputs.TAG }}